import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { useStats } from "@/hooks/useStats";
import { useAuth } from "@/hooks/useAuth";
import { Link } from "wouter";
import { Lock, Unlock } from "lucide-react";
import { SignInButton } from '@clerk/clerk-react';
import AuthHeader from "./AuthHeader";

interface SidebarProps {
  coordinates: { lat: number; lng: number } | null;
  generatedLink: { webLink: string; emailLink: string } | null;
  onLinkGenerated: (link: { webLink: string; emailLink: string }) => void;
}

export default function Sidebar({ coordinates, generatedLink, onLinkGenerated }: SidebarProps) {
  const [email, setEmail] = useState("");
  const [otpCode, setOtpCode] = useState("");
  const [editToken, setEditToken] = useState("");
  const [showOtpInput, setShowOtpInput] = useState(false);
  const { toast } = useToast();
  const { data: stats, isLoading: statsLoading } = useStats();
  const auth = useAuth();

  const generatePinMutation = useMutation({
    mutationFn: async () => {
      if (!coordinates) throw new Error("No coordinates set");
      if (!auth.isAuthenticated) throw new Error("Please login to create pins");
      
      const response = await apiRequest("POST", "/api/pins", {
        latitude: coordinates.lat.toString(),
        longitude: coordinates.lng.toString(),
        shortcode: "", // Will be generated by server
      });
      return response.json();
    },
    onSuccess: (data) => {
      onLinkGenerated({
        webLink: data.webLink,
        emailLink: data.emailLink,
      });
      toast({
        title: "AddyPin Generated!",
        description: "Your short link is ready to share.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to generate link",
        variant: "destructive",
      });
    },
  });

  const sendOtpMutation = useMutation({
    mutationFn: async (email: string) => {
      const response = await apiRequest("POST", "/api/otp/send", { email });
      return response.json();
    },
    onSuccess: () => {
      setShowOtpInput(true);
      toast({
        title: "OTP Sent",
        description: "Check your email for the verification code (or console in development)",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to send OTP",
        variant: "destructive",
      });
    },
  });

  const verifyOtpMutation = useMutation({
    mutationFn: async ({ email, code }: { email: string; code: string }) => {
      const response = await apiRequest("POST", "/api/otp/verify", { email, code });
      return response.json();
    },
    onSuccess: (data) => {
      setEditToken(data.editToken);
      toast({
        title: "Verified",
        description: "You can now edit pin coordinates",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Invalid OTP",
        variant: "destructive",
      });
    },
  });

  const sendEmailMutation = useMutation({
    mutationFn: async () => {
      if (!coordinates || !email) throw new Error("Missing coordinates or email");
      
      const response = await apiRequest("POST", "/api/send-location", {
        email,
        latitude: coordinates.lat.toString(),
        longitude: coordinates.lng.toString(),
        shortcode: generatedLink ? generatedLink.webLink.split('.')[0] : undefined,
      });
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: "Email Sent!",
        description: "Location details have been sent to your email.",
      });
      setEmail("");
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to send email",
        variant: "destructive",
      });
    },
  });

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast({
        title: "Copied!",
        description: "Link copied to clipboard.",
      });
    } catch (err) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="lg:col-span-1 space-y-6">
      {/* Short Link Generator */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
          <i className="fas fa-link text-addypin-cyan mr-3"></i>
          Generate Short Link
        </h2>

        {!auth.isAuthenticated ? (
          <div className="space-y-3">
            <p className="text-sm text-amber-700 bg-amber-50 p-3 rounded-lg border border-amber-200 flex items-center">
              <Lock className="w-4 h-4 mr-2" />
              Login required to create pins
            </p>
            <SignInButton mode="modal">
              <Button 
                className="w-full bg-addypin-cyan hover:bg-cyan-600 text-white font-semibold py-4 px-6 rounded-lg transition-all duration-200"
                data-testid="button-login-to-create"
              >
                <Lock className="w-4 h-4 mr-2" />
                Login to Create Pin
              </Button>
            </SignInButton>
          </div>
        ) : (
          <Button
            onClick={() => generatePinMutation.mutate()}
            disabled={!coordinates || generatePinMutation.isPending}
            className="w-full bg-addypin-cyan hover:bg-cyan-600 text-white font-semibold py-4 px-6 rounded-lg transition-all duration-200 transform hover:scale-105 active:scale-95 shadow-lg hover:shadow-xl mb-4"
            data-testid="button-generate"
          >
            <i className="fas fa-magic mr-2"></i>
            {generatePinMutation.isPending ? "Generating..." : "Generate AddyPin"}
          </Button>
        )}

        {generatedLink && (
          <div className="space-y-3">
            <div>
              <Label className="block text-xs font-medium text-addypin-medium mb-1">
                Web Link
              </Label>
              <div className="flex items-center bg-addypin-light rounded-lg p-3">
                <Input
                  type="text"
                  value={generatedLink.webLink}
                  readOnly
                  className="flex-1 bg-transparent text-sm font-mono text-addypin-dark border-none p-0 focus-visible:ring-0"
                  data-testid="input-web-link"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => copyToClipboard(generatedLink.webLink)}
                  className="ml-2 text-addypin-cyan hover:text-cyan-600 h-auto p-1"
                  data-testid="button-copy-web-link"
                >
                  <i className="fas fa-copy"></i>
                </Button>
              </div>
            </div>

            <div>
              <Label className="block text-xs font-medium text-addypin-medium mb-1">
                Email Format
              </Label>
              <div className="flex items-center bg-addypin-light rounded-lg p-3">
                <Input
                  type="text"
                  value={generatedLink.emailLink}
                  readOnly
                  className="flex-1 bg-transparent text-sm font-mono text-addypin-dark border-none p-0 focus-visible:ring-0"
                  data-testid="input-email-link"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => copyToClipboard(generatedLink.emailLink)}
                  className="ml-2 text-addypin-cyan hover:text-cyan-600 h-auto p-1"
                  data-testid="button-copy-email-link"
                >
                  <i className="fas fa-copy"></i>
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Quick Stats */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4">📊 Quick Stats</h2>

        <div className="grid grid-cols-2 gap-3">
          <div className="stats-card rounded-lg p-3">
            <div className="flex items-center">
              <div className="w-8 h-8 bg-addypin-cyan bg-opacity-10 rounded-lg flex items-center justify-center mr-3">
                📍
              </div>
              <div>
                <p className="text-xs font-medium text-addypin-medium">Today</p>
                <p className="text-lg font-bold text-addypin-dark" data-testid="text-pins-today">
                  {statsLoading ? "..." : (stats as any)?.pinsCreated || 0}
                </p>
              </div>
            </div>
          </div>

          <div className="stats-card rounded-lg p-3">
            <div className="flex items-center">
              <div className="w-8 h-8 bg-gray-100 rounded-lg flex items-center justify-center mr-3">
                🗺️
              </div>
              <div>
                <p className="text-xs font-medium text-addypin-medium">Total</p>
                <p className="text-lg font-bold text-addypin-dark" data-testid="text-total-pins">
                  {statsLoading ? "..." : (stats as any)?.totalPins || 0}
                </p>
              </div>
            </div>
          </div>

          <div className="stats-card rounded-lg p-3">
            <div className="flex items-center">
              <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center mr-3">
                👆
              </div>
              <div>
                <p className="text-xs font-medium text-addypin-medium">Clicks</p>
                <p className="text-lg font-bold text-addypin-dark" data-testid="text-links-clicked">
                  {statsLoading ? "..." : (stats as any)?.linksClicked || 0}
                </p>
              </div>
            </div>
          </div>

          <div className="stats-card rounded-lg p-3">
            <div className="flex items-center">
              <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center mr-3">
                🌍
              </div>
              <div>
                <p className="text-xs font-medium text-addypin-medium">Countries</p>
                <p className="text-lg font-bold text-addypin-dark" data-testid="text-active-countries">
                  {statsLoading ? "..." : (stats as any)?.activeCountries || 0}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Top Map Apps */}
        <div className="mt-4 pt-4 border-t border-gray-200">
          <p className="text-sm font-medium text-addypin-dark mb-3">🏆 Top Map Apps</p>
          <div className="space-y-2">
            {(statsLoading ? [] : (stats as any)?.topMapApps || []).slice(0, 3).map((app: any, index: number) => (
              <div key={app.name} className="flex items-center justify-between">
                <div className="flex items-center">
                  <span className="w-5 h-5 text-xs flex items-center justify-center bg-addypin-light rounded text-addypin-dark mr-2">
                    {index + 1}
                  </span>
                  <span className="text-sm text-addypin-dark">{app.name}</span>
                </div>
                <span className="text-sm font-medium text-addypin-cyan">{app.clicks}</span>
              </div>
            ))}
            {statsLoading && (
              <div className="text-sm text-addypin-medium">Loading...</div>
            )}
          </div>
        </div>
      </div>

      {/* Email Integration */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
          <i className="fas fa-envelope text-addypin-cyan mr-3"></i>
          Email Integration
        </h2>

        <div className="space-y-4">
          <div>
            <Input
              type="email"
              placeholder="your@email.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg text-addypin-dark focus:ring-2 focus:ring-addypin-cyan focus:border-transparent transition-colors"
              data-testid="input-email"
            />
          </div>

          <Button
            onClick={() => sendEmailMutation.mutate()}
            disabled={!email || !coordinates || sendEmailMutation.isPending}
            className="w-full bg-gray-100 hover:bg-addypin-cyan hover:text-white text-addypin-dark font-medium py-3 px-4 rounded-lg transition-all duration-200 border border-gray-300 hover:border-addypin-cyan"
            data-testid="button-send-email"
          >
            <i className="fas fa-paper-plane mr-2"></i>
            {sendEmailMutation.isPending ? "Sending..." : "Send Location via Email"}
          </Button>

          <p className="text-xs text-addypin-medium">
            Get coordinates and map links delivered to your inbox
          </p>
        </div>
      </div>

      {/* Coordinate Editing Section */}
      {generatedLink && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <h3 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
            <Unlock className="w-5 h-5 text-addypin-cyan mr-3" />
            Edit Coordinates
          </h3>

          <div className="space-y-4">
            <p className="text-sm text-gray-600">
              To edit pin coordinates, verify your email address with OTP.
            </p>
            
            <div>
              <Label htmlFor="edit-email" className="block text-sm font-medium text-addypin-dark mb-2">
                Email for verification
              </Label>
              <div className="flex space-x-2">
                <Input
                  id="edit-email"
                  type="email"
                  placeholder="your@email.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="flex-1 border-gray-300 focus:border-addypin-cyan focus:ring-addypin-cyan"
                  data-testid="input-edit-email"
                />
                <Button
                  onClick={() => sendOtpMutation.mutate(email)}
                  disabled={!email || sendOtpMutation.isPending}
                  className="bg-addypin-cyan hover:bg-cyan-600 text-white px-4"
                  data-testid="button-send-otp"
                >
                  {sendOtpMutation.isPending ? "Sending..." : "Send OTP"}
                </Button>
              </div>
            </div>

            {showOtpInput && (
              <div>
                <Label htmlFor="otp-code" className="block text-sm font-medium text-addypin-dark mb-2">
                  Verification Code
                </Label>
                <div className="flex space-x-2">
                  <Input
                    id="otp-code"
                    type="text"
                    placeholder="123456"
                    value={otpCode}
                    onChange={(e) => setOtpCode(e.target.value)}
                    maxLength={6}
                    className="flex-1 border-gray-300 focus:border-addypin-cyan focus:ring-addypin-cyan font-mono"
                    data-testid="input-otp-code"
                  />
                  <Button
                    onClick={() => verifyOtpMutation.mutate({ email, code: otpCode })}
                    disabled={!otpCode || verifyOtpMutation.isPending}
                    className="bg-green-600 hover:bg-green-700 text-white px-4"
                    data-testid="button-verify-otp"
                  >
                    {verifyOtpMutation.isPending ? "Verifying..." : "Verify"}
                  </Button>
                </div>
              </div>
            )}

            {editToken && (
              <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                <p className="text-sm text-green-700 flex items-center">
                  <Unlock className="w-4 h-4 mr-2" />
                  Verified! You can now edit coordinates by clicking on the map.
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="text-center mt-6">
        {/* Empty footer space - Version History moved to Home page Resources */}
      </div>
    </div>
  );
}
