import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { useStats } from "@/hooks/useStats";

interface SidebarProps {
  coordinates: { lat: number; lng: number } | null;
  generatedLink: { webLink: string; emailLink: string } | null;
  onLinkGenerated: (link: { webLink: string; emailLink: string }) => void;
}

export default function Sidebar({ coordinates, generatedLink, onLinkGenerated }: SidebarProps) {
  const [email, setEmail] = useState("");
  const { toast } = useToast();
  const { data: stats, isLoading: statsLoading } = useStats();

  const generatePinMutation = useMutation({
    mutationFn: async () => {
      if (!coordinates) throw new Error("No coordinates set");
      
      const response = await apiRequest("POST", "/api/pins", {
        latitude: coordinates.lat.toString(),
        longitude: coordinates.lng.toString(),
        shortcode: "", // Will be generated by server
      });
      return response.json();
    },
    onSuccess: (data) => {
      onLinkGenerated({
        webLink: data.webLink,
        emailLink: data.emailLink,
      });
      toast({
        title: "AddyPin Generated!",
        description: "Your short link is ready to share.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to generate link",
        variant: "destructive",
      });
    },
  });

  const sendEmailMutation = useMutation({
    mutationFn: async () => {
      if (!coordinates || !email) throw new Error("Missing coordinates or email");
      
      const response = await apiRequest("POST", "/api/send-location", {
        email,
        latitude: coordinates.lat.toString(),
        longitude: coordinates.lng.toString(),
        shortcode: generatedLink ? generatedLink.webLink.split('.')[0] : undefined,
      });
      return response.json();
    },
    onSuccess: () => {
      toast({
        title: "Email Sent!",
        description: "Location details have been sent to your email.",
      });
      setEmail("");
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to send email",
        variant: "destructive",
      });
    },
  });

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast({
        title: "Copied!",
        description: "Link copied to clipboard.",
      });
    } catch (err) {
      toast({
        title: "Error",
        description: "Failed to copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="lg:col-span-1 space-y-6">
      {/* Short Link Generator */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
          <i className="fas fa-link text-addypin-cyan mr-3"></i>
          Generate Short Link
        </h2>

        <Button
          onClick={() => generatePinMutation.mutate()}
          disabled={!coordinates || generatePinMutation.isPending}
          className="w-full bg-addypin-cyan hover:bg-cyan-600 text-white font-semibold py-4 px-6 rounded-lg transition-all duration-200 transform hover:scale-105 active:scale-95 shadow-lg hover:shadow-xl mb-4"
          data-testid="button-generate"
        >
          <i className="fas fa-magic mr-2"></i>
          {generatePinMutation.isPending ? "Generating..." : "Generate AddyPin"}
        </Button>

        {generatedLink && (
          <div className="space-y-3">
            <div>
              <Label className="block text-xs font-medium text-addypin-medium mb-1">
                Web Link
              </Label>
              <div className="flex items-center bg-addypin-light rounded-lg p-3">
                <Input
                  type="text"
                  value={generatedLink.webLink}
                  readOnly
                  className="flex-1 bg-transparent text-sm font-mono text-addypin-dark border-none p-0 focus-visible:ring-0"
                  data-testid="input-web-link"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => copyToClipboard(generatedLink.webLink)}
                  className="ml-2 text-addypin-cyan hover:text-cyan-600 h-auto p-1"
                  data-testid="button-copy-web-link"
                >
                  <i className="fas fa-copy"></i>
                </Button>
              </div>
            </div>

            <div>
              <Label className="block text-xs font-medium text-addypin-medium mb-1">
                Email Format
              </Label>
              <div className="flex items-center bg-addypin-light rounded-lg p-3">
                <Input
                  type="text"
                  value={generatedLink.emailLink}
                  readOnly
                  className="flex-1 bg-transparent text-sm font-mono text-addypin-dark border-none p-0 focus-visible:ring-0"
                  data-testid="input-email-link"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => copyToClipboard(generatedLink.emailLink)}
                  className="ml-2 text-addypin-cyan hover:text-cyan-600 h-auto p-1"
                  data-testid="button-copy-email-link"
                >
                  <i className="fas fa-copy"></i>
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Quick Stats */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
          <i className="fas fa-chart-bar text-addypin-cyan mr-3"></i>
          Quick Stats
        </h2>

        <div className="space-y-4">
          <div className="stats-card rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-addypin-medium">Pins Created Today</p>
                <p className="text-2xl font-bold text-addypin-dark" data-testid="text-pins-today">
                  {statsLoading ? "..." : (stats as any)?.pinsCreated || 0}
                </p>
              </div>
              <div className="w-12 h-12 bg-addypin-cyan bg-opacity-10 rounded-lg flex items-center justify-center">
                <i className="fas fa-map-pin text-addypin-cyan text-xl"></i>
              </div>
            </div>
          </div>

          <div className="stats-card rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-addypin-medium">Links Clicked</p>
                <p className="text-2xl font-bold text-addypin-dark" data-testid="text-links-clicked">
                  {statsLoading ? "..." : (stats as any)?.linksClicked || 0}
                </p>
              </div>
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                <i className="fas fa-mouse-pointer text-green-600 text-xl"></i>
              </div>
            </div>
          </div>

          <div className="stats-card rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-addypin-medium">Active Countries</p>
                <p className="text-2xl font-bold text-addypin-dark" data-testid="text-active-countries">
                  {statsLoading ? "..." : (stats as any)?.activeCountries || 0}
                </p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <i className="fas fa-globe-americas text-blue-600 text-xl"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Email Integration */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-addypin-dark mb-4 flex items-center">
          <i className="fas fa-envelope text-addypin-cyan mr-3"></i>
          Email Integration
        </h2>

        <div className="space-y-4">
          <div>
            <Input
              type="email"
              placeholder="your@email.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg text-addypin-dark focus:ring-2 focus:ring-addypin-cyan focus:border-transparent transition-colors"
              data-testid="input-email"
            />
          </div>

          <Button
            onClick={() => sendEmailMutation.mutate()}
            disabled={!email || !coordinates || sendEmailMutation.isPending}
            className="w-full bg-gray-100 hover:bg-addypin-cyan hover:text-white text-addypin-dark font-medium py-3 px-4 rounded-lg transition-all duration-200 border border-gray-300 hover:border-addypin-cyan"
            data-testid="button-send-email"
          >
            <i className="fas fa-paper-plane mr-2"></i>
            {sendEmailMutation.isPending ? "Sending..." : "Send Location via Email"}
          </Button>

          <p className="text-xs text-addypin-medium">
            Get coordinates and map links delivered to your inbox
          </p>
        </div>
      </div>
    </div>
  );
}
